2022-01-17 13:46:58,056 - ERROR - baseApi.py[59]:Traceback (most recent call last):
  File "D:\study\Test3\commcon\baseApi.py", line 52, in define_api_assert
    assert result == exp_result
AssertionError

