2022-01-17 11:48:04,618 - ERROR - baseApi.py[59]:Traceback (most recent call last):
  File "D:\study\Test3\commcon\baseApi.py", line 52, in define_api_assert
    assert result == exp_result
AssertionError

2022-01-17 11:48:05,076 - ERROR - baseApi.py[59]:Traceback (most recent call last):
  File "D:\study\Test3\commcon\baseApi.py", line 52, in define_api_assert
    assert result == exp_result
AssertionError

2022-01-17 11:48:05,450 - ERROR - baseApi.py[59]:Traceback (most recent call last):
  File "D:\study\Test3\commcon\baseApi.py", line 52, in define_api_assert
    assert result == exp_result
AssertionError

2022-01-17 11:48:05,604 - ERROR - baseApi.py[59]:Traceback (most recent call last):
  File "D:\study\Test3\commcon\baseApi.py", line 52, in define_api_assert
    assert result == exp_result
AssertionError

2022-01-17 11:48:05,750 - ERROR - baseApi.py[59]:Traceback (most recent call last):
  File "D:\study\Test3\commcon\baseApi.py", line 52, in define_api_assert
    assert result == exp_result
AssertionError

