2022-01-28 09:42:16,530 - ERROR - baseApi.py[60]:Traceback (most recent call last):
  File "D:\AutoTextAPI\commcon\baseApi.py", line 53, in define_api_assert
    assert result == exp_result
AssertionError

2022-01-28 09:42:16,580 - ERROR - baseApi.py[60]:Traceback (most recent call last):
  File "D:\AutoTextAPI\commcon\baseApi.py", line 53, in define_api_assert
    assert result == exp_result
AssertionError

2022-01-28 09:42:16,700 - ERROR - baseApi.py[60]:Traceback (most recent call last):
  File "D:\AutoTextAPI\commcon\baseApi.py", line 53, in define_api_assert
    assert result == exp_result
AssertionError

